### ISSUE TITLE
[RFC][Trade protocol] Specify also a fixed fee along with (basis point) fee

### ISSUE THREAD

**Issue by tiero** [TDex-network/tdex-specs#24]
## Context

In the `tdex-daemon` we subsidize all the incoming trade's blockchain fees: this permits a great UX for end users (ie. no need to have LBTC in the wallet first if I want to swap USDT)

It could happens that a Liquidity Provider want to charge also a fixed amount for each trade (mostly to cover transaction fee subsidize) and discourage low amount trading that with a reasonable percentage fee is not "covering" the LBTC needed to pay for the swap transaction.

## Proposal

I propose to edit `Fee` at https://github.com/TDex-network/tdex-protobuf/blob/beta/types.proto#L5  like the following:

```proto
message Fee {
  int64 basis_point = 2;
  Fixed fixed = 3;
}

message Fixed {
  base_fee = 1;
  quote_fee = 2;
}

```

This way we can know how much to charge in case the asset "on the way in" is one or another. 

Let's say we have L-BTC-USDt pair, I would put `650` (the average cost for a swap tx)  and `20 000 000` for USDt (arounf 20 cents per swap a current price)

**Comment by altafan** [comment]
Ack
